name: optimize
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.12
  flutter_html: ^2.2.0
  photo_view: ^0.14.0
  flutter_cached_pdfview: ^0.4.1
  fijkplayer: ^0.10.1
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.1
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.8
  audio_video_progress_bar: ^0.10.0
  audioplayers: ^1.0.1
  firebase_core: ^1.10.6
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^10.0.0-dev.1
  firebase_auth: ^3.3.4
  transparent_image: ^2.0.0
  youtube_player_flutter: ^8.0.0
  firebase_app_check: ^0.0.6+7
  comment_box: ^0.0.17

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Acumin
      fonts:
        - asset: assets/fonts/Acumin-RPro.otf
        - asset: assets/fonts/Acumin-BdPro.otf
          weight: 700
        - asset: assets/fonts/Acumin-BdItPro.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Acumin-ItPro.otf
          style: italic
